#ifndef UICONFIG_H_
#define UICONFIG_H_
//单人捕鱼场
#define Form_buyuchang   0
#define buyuchang_control1   0
#define buyuchang_control2   1
#define buyuchang_control3   2
#define buyuchang_control4   3
#define buyuchang_control5   4
#define buyuchang_control6   5
#define buyuchang_control7   6
#define buyuchang_control8   7
#define buyuchang_control9   8
#define buyuchang_control10   9
#define buyuchang_control11   10
#define buyuchang_control12   11
#define buyuchang_control13   12
#define buyuchang_control14   13
#define buyuchang_control15   14
#define buyuchang_control16   15
#define buyuchang_control17   16
#define buyuchang_control18   17
#define buyuchang_control19   18
#define buyuchang_control20   19
#define buyuchang_control21   20
#define buyuchang_control22   21
#define buyuchang_control23   22
#define buyuchang_control24   23
#define buyuchang_control25   24
#define buyuchang_control26   25
#define buyuchang_control27   26
#define buyuchang_control28   27
#define buyuchang_control29   28
#define buyuchang_control30   29
#define buyuchang_control31   30
#define buyuchang_control32   31
#define buyuchang_control33   32
#define buyuchang_control34   33
#define buyuchang_control35   34
#define buyuchang_control36   35
#define buyuchang_control37   36
#define buyuchang_control38   37
#define buyuchang_control39   38
#define buyuchang_control40   39
#define buyuchang_control41   40
#define buyuchang_control42   41
#define buyuchang_control43   42
#define buyuchang_control44   43
#define buyuchang_control45   44

//多人捕鱼场
#define Form_duorenbuyuchang   1
#define duorenbuyuchang_control1   0
#define duorenbuyuchang_control2   1
#define duorenbuyuchang_control3   2
#define duorenbuyuchang_control4   3
#define duorenbuyuchang_control5   4
#define duorenbuyuchang_control6   5
#define duorenbuyuchang_control7   6
#define duorenbuyuchang_control8   7
#define duorenbuyuchang_control9   8
#define duorenbuyuchang_control10   9
#define duorenbuyuchang_control11   10
#define duorenbuyuchang_control12   11
#define duorenbuyuchang_control13   12
#define duorenbuyuchang_control14   13
#define duorenbuyuchang_control15   14
#define duorenbuyuchang_control16   15
#define duorenbuyuchang_control17   16
#define duorenbuyuchang_control18   17
#define duorenbuyuchang_control19   18
#define duorenbuyuchang_control20   19
#define duorenbuyuchang_control21   20
#define duorenbuyuchang_control22   21
#define duorenbuyuchang_control23   22
#define duorenbuyuchang_control24   23
#define duorenbuyuchang_control25   24
#define duorenbuyuchang_control26   25
#define duorenbuyuchang_control27   26
#define duorenbuyuchang_control28   27
#define duorenbuyuchang_control29   28
#define duorenbuyuchang_control30   29
#define duorenbuyuchang_control31   30
#define duorenbuyuchang_control32   31
#define duorenbuyuchang_control33   32
#define duorenbuyuchang_control34   33
#define duorenbuyuchang_control35   34
#define duorenbuyuchang_control36   35
#define duorenbuyuchang_control37   36
#define duorenbuyuchang_control38   37
#define duorenbuyuchang_control39   38
#define duorenbuyuchang_control40   39
#define duorenbuyuchang_control41   40
#define duorenbuyuchang_control42   41
#define duorenbuyuchang_control43   42
#define duorenbuyuchang_control44   43
#define duorenbuyuchang_control45   44
#define duorenbuyuchang_control46   45
#define duorenbuyuchang_control47   46
#define duorenbuyuchang_control48   47
#define duorenbuyuchang_control49   48
#define duorenbuyuchang_control50   49
#define duorenbuyuchang_control51   50
#define duorenbuyuchang_control52   51
#define duorenbuyuchang_control53   52
#define duorenbuyuchang_control54   53
#define duorenbuyuchang_control55   54
#define duorenbuyuchang_control56   55
#define duorenbuyuchang_control57   56
#define duorenbuyuchang_control58   57
#define duorenbuyuchang_control59   58
#define duorenbuyuchang_control60   59
#define duorenbuyuchang_control61   60
#define duorenbuyuchang_control62   61
#define duorenbuyuchang_control63   62
#define duorenbuyuchang_control64   63
#define duorenbuyuchang_control65   64
#define duorenbuyuchang_control66   65

//单人模式选关
#define Form_danrenmoshixuanguan   2
#define danrenmoshixuanguan_control1   0
#define danrenmoshixuanguan_control2   1
#define danrenmoshixuanguan_control3   2
#define danrenmoshixuanguan_control4   3
#define danrenmoshixuanguan_control5   4
#define danrenmoshixuanguan_control6   5
#define danrenmoshixuanguan_control7   6
#define danrenmoshixuanguan_control8   7
#define danrenmoshixuanguan_control9   8

//任务弹框
#define Form_renwutankuang   3
#define renwutankuang_control1   0
#define renwutankuang_control2   1
#define renwutankuang_control3   2
#define renwutankuang_control4   3
#define renwutankuang_control5   4

//更换炮台
#define Form_genghuanpaotai   4
#define genghuanpaotai_control1   0
#define genghuanpaotai_control2   1
#define genghuanpaotai_control3   2
#define genghuanpaotai_control4   3
#define genghuanpaotai_control5   4
#define genghuanpaotai_control6   5
#define genghuanpaotai_control7   6
#define genghuanpaotai_control8   7
#define genghuanpaotai_control9   8
#define genghuanpaotai_control10   9

//道具说明
#define Form_daojushuoming   5
#define daojushuoming_control1   0
#define daojushuoming_control2   1
#define daojushuoming_control3   2
#define daojushuoming_control4   3
#define daojushuoming_control5   4
#define daojushuoming_control6   5
#define daojushuoming_control7   6
#define daojushuoming_control8   7
#define daojushuoming_control9   8
#define daojushuoming_control10   9
#define daojushuoming_control11   10
#define daojushuoming_control12   11

//倍率介绍
#define Form_beilvjieshao   6
#define beilvjieshao_control1   0
#define beilvjieshao_control2   1
#define beilvjieshao_control3   2
#define beilvjieshao_control4   3
#define beilvjieshao_control5   4
#define beilvjieshao_control6   5
#define beilvjieshao_control7   6
#define beilvjieshao_control8   7
#define beilvjieshao_control9   8
#define beilvjieshao_control10   9
#define beilvjieshao_control11   10

//在线奖励
#define Form_zaixianjiangli   7
#define zaixianjiangli_control1   0
#define zaixianjiangli_control2   1
#define zaixianjiangli_control3   2
#define zaixianjiangli_control4   3
#define zaixianjiangli_control5   4
#define zaixianjiangli_control6   5
#define zaixianjiangli_control7   6
#define zaixianjiangli_control8   7
#define zaixianjiangli_control9   8
#define zaixianjiangli_control10   9
#define zaixianjiangli_control11   10
#define zaixianjiangli_control12   11
#define zaixianjiangli_control13   12
#define zaixianjiangli_control14   13
#define zaixianjiangli_control15   14
#define zaixianjiangli_control16   15
#define zaixianjiangli_control17   16

//多人模式选关
#define Form_duorenmoshixuanguan   8
#define duorenmoshixuanguan_control1   0
#define duorenmoshixuanguan_control2   1
#define duorenmoshixuanguan_control3   2
#define duorenmoshixuanguan_control4   3
#define duorenmoshixuanguan_control5   4
#define duorenmoshixuanguan_control6   5
#define duorenmoshixuanguan_control7   6
#define duorenmoshixuanguan_control8   7
#define duorenmoshixuanguan_control9   8
#define duorenmoshixuanguan_control10   9
#define duorenmoshixuanguan_control11   10
#define duorenmoshixuanguan_control15   11
#define duorenmoshixuanguan_control16   12
#define duorenmoshixuanguan_control17   13
#define duorenmoshixuanguan_control18   14
#define duorenmoshixuanguan_control19   15
#define duorenmoshixuanguan_control20   16

//VIP提示弹框
#define Form_VIPtishitankuang   9
#define VIPtishitankuang_control1   0
#define VIPtishitankuang_control2   1
#define VIPtishitankuang_control3   2
#define VIPtishitankuang_control4   3
#define VIPtishitankuang_control5   4
#define VIPtishitankuang_control6   5

//封面
#define Form_fengmian   10
#define fengmian_control1   0
#define fengmian_control2   1
#define fengmian_control3   2
#define fengmian_control4   3
#define fengmian_control5   4
#define fengmian_control6   5
#define fengmian_control7   6
#define fengmian_control8   7
#define fengmian_control9   8
#define fengmian_control10   9
#define fengmian_control11   10
#define fengmian_control12   11
#define fengmian_control13   12
#define fengmian_control14   13
#define fengmian_control15   14
#define fengmian_control16   15
#define fengmian_control17   16
#define fengmian_control18   17
#define fengmian_control19   18
#define fengmian_control20   19
#define fengmian_control21   20
#define fengmian_control22   21
#define fengmian_control23   22
#define fengmian_control24   23
#define fengmian_control25   24
#define fengmian_control26   25
#define fengmian_control27   26
#define fengmian_control28   27
#define fengmian_control29   28

//每日签到
#define Form_meiriqiandao   11
#define meiriqiandao_control1   0
#define meiriqiandao_control2   1
#define meiriqiandao_control3   2
#define meiriqiandao_control4   3
#define meiriqiandao_control5   4
#define meiriqiandao_control6   5
#define meiriqiandao_control7   6
#define meiriqiandao_control8   7
#define meiriqiandao_control9   8
#define meiriqiandao_control10   9
#define meiriqiandao_control11   10
#define meiriqiandao_control12   11
#define meiriqiandao_control13   12
#define meiriqiandao_control14   13
#define meiriqiandao_control15   14
#define meiriqiandao_control16   15
#define meiriqiandao_control17   16
#define meiriqiandao_control18   17
#define meiriqiandao_control19   18
#define meiriqiandao_control20   19
#define meiriqiandao_control21   20
#define meiriqiandao_control22   21
#define meiriqiandao_control23   22
#define meiriqiandao_control24   23
#define meiriqiandao_control25   24
#define meiriqiandao_control26   25
#define meiriqiandao_control27   26
#define meiriqiandao_control28   27
#define meiriqiandao_control29   28
#define meiriqiandao_control30   29
#define meiriqiandao_control31   30
#define meiriqiandao_control32   31
#define meiriqiandao_control33   32
#define meiriqiandao_control34   33
#define meiriqiandao_control35   34
#define meiriqiandao_control36   35
#define meiriqiandao_control37   36
#define meiriqiandao_control38   37
#define meiriqiandao_control39   38
#define meiriqiandao_control40   39
#define meiriqiandao_control41   40
#define meiriqiandao_control42   41
#define meiriqiandao_control43   42
#define meiriqiandao_control44   43
#define meiriqiandao_control45   44
#define meiriqiandao_control46   45
#define meiriqiandao_control47   46

//排行榜
#define Form_paihangbang   12
#define paihangbang_control1   0
#define paihangbang_control2   1
#define paihangbang_control3   2
#define paihangbang_control4   3
#define paihangbang_control5   4
#define paihangbang_control6   5
#define paihangbang_control7   6
#define paihangbang_control8   7
#define paihangbang_control9   8
#define paihangbang_control10   9
#define paihangbang_control11   10
#define paihangbang_control13   11
#define paihangbang_control14   12
#define paihangbang_control15   13
#define paihangbang_control18   14
#define paihangbang_control19   15
#define paihangbang_control20   16
#define paihangbang_control23   17
#define paihangbang_control24   18
#define paihangbang_control25   19
#define paihangbang_control28   20
#define paihangbang_control29   21
#define paihangbang_control30   22
#define paihangbang_control33   23
#define paihangbang_control34   24
#define paihangbang_control35   25
#define paihangbang_control40   26
#define paihangbang_control41   27
#define paihangbang_control42   28
#define paihangbang_control43   29
#define paihangbang_control44   30
#define paihangbang_control45   31
#define paihangbang_control46   32
#define paihangbang_control47   33
#define paihangbang_control49   34
#define paihangbang_control50   35
#define paihangbang_control16   36
#define paihangbang_control36   37
#define paihangbang_control51   38
#define paihangbang_control53   39
#define paihangbang_control54   40
#define paihangbang_control21   41
#define paihangbang_control26   42
#define paihangbang_control37   43
#define paihangbang_control55   44
#define paihangbang_control56   45
#define paihangbang_control31   46
#define paihangbang_control38   47
#define paihangbang_control57   48
#define paihangbang_control59   49
#define paihangbang_control60   50
#define paihangbang_control48   51
#define paihangbang_control39   52
#define paihangbang_control58   53
#define paihangbang_control52   54
#define paihangbang_control12   55
#define paihangbang_control62   56
#define paihangbang_control63   57
#define paihangbang_control64   58
#define paihangbang_control65   59
#define paihangbang_control61   60
#define paihangbang_control27   61
#define paihangbang_control66   62
#define paihangbang_control67   63
#define paihangbang_control68   64
#define paihangbang_control69   65
#define paihangbang_control70   66
#define paihangbang_control71   67
#define paihangbang_control72   68
#define paihangbang_control73   69
#define paihangbang_control74   70
#define paihangbang_control75   71
#define paihangbang_control76   72
#define paihangbang_control17   73
#define paihangbang_control32   74
#define paihangbang_control77   75
#define paihangbang_control78   76
#define paihangbang_control79   77
#define paihangbang_control80   78
#define paihangbang_control81   79
#define paihangbang_control82   80
#define paihangbang_control83   81
#define paihangbang_control84   82
#define paihangbang_control85   83
#define paihangbang_control86   84

//个人信息
#define Form_gerenxinxi   13
#define gerenxinxi_control1   0
#define gerenxinxi_control2   1
#define gerenxinxi_control3   2
#define gerenxinxi_control4   3
#define gerenxinxi_control5   4
#define gerenxinxi_control6   5
#define gerenxinxi_control7   6
#define gerenxinxi_control8   7
#define gerenxinxi_control9   8
#define gerenxinxi_control10   9
#define gerenxinxi_control11   10
#define gerenxinxi_control12   11
#define gerenxinxi_control13   12
#define gerenxinxi_control14   13
#define gerenxinxi_control15   14
#define gerenxinxi_control16   15
#define gerenxinxi_control17   16
#define gerenxinxi_control18   17
#define gerenxinxi_control19   18
#define gerenxinxi_control20   19

//登陆窗口
#define Form_dengluchuangkou   14
#define dengluchuangkou_control1   0
#define dengluchuangkou_control2   1
#define dengluchuangkou_control3   2
#define dengluchuangkou_control4   3
#define dengluchuangkou_control5   4
#define dengluchuangkou_control6   5
#define dengluchuangkou_control7   6
#define dengluchuangkou_control10   7
#define dengluchuangkou_control11   8
#define dengluchuangkou_control12   9
#define dengluchuangkou_control13   10
#define dengluchuangkou_control14   11
#define dengluchuangkou_control15   12
#define dengluchuangkou_control16   13
#define dengluchuangkou_control17   14
#define dengluchuangkou_control18   15
#define dengluchuangkou_control19   16
#define dengluchuangkou_control8   17
#define dengluchuangkou_control9   18
#define dengluchuangkou_control20   19
#define dengluchuangkou_control21   20

//金币商城
#define Form_jingbishangcheng   15
#define jingbishangcheng_control1   0
#define jingbishangcheng_control2   1
#define jingbishangcheng_control3   2
#define jingbishangcheng_control4   3
#define jingbishangcheng_control5   4
#define jingbishangcheng_control6   5
#define jingbishangcheng_control7   6
#define jingbishangcheng_control8   7
#define jingbishangcheng_control9   8
#define jingbishangcheng_control10   9
#define jingbishangcheng_control11   10
#define jingbishangcheng_control12   11
#define jingbishangcheng_control13   12
#define jingbishangcheng_control14   13
#define jingbishangcheng_control15   14
#define jingbishangcheng_control16   15
#define jingbishangcheng_control17   16
#define jingbishangcheng_control18   17
#define jingbishangcheng_control19   18
#define jingbishangcheng_control20   19
#define jingbishangcheng_control21   20
#define jingbishangcheng_control22   21
#define jingbishangcheng_control23   22
#define jingbishangcheng_control24   23
#define jingbishangcheng_control25   24
#define jingbishangcheng_control26   25
#define jingbishangcheng_control27   26
#define jingbishangcheng_control28   27
#define jingbishangcheng_control29   28
#define jingbishangcheng_control30   29
#define jingbishangcheng_control31   30

//过关
#define Form_gameend   16
#define gameend_control1   0
#define gameend_control2   1
#define gameend_control3   2
#define gameend_control4   3
#define gameend_control5   4

//解锁炮弹
#define Form_jiesuopaodan   17
#define jiesuopaodan_control1   0
#define jiesuopaodan_control2   1
#define jiesuopaodan_control3   2
#define jiesuopaodan_control4   3
#define jiesuopaodan_control5   4
#define jiesuopaodan_control6   5
#define jiesuopaodan_control7   6
#define jiesuopaodan_control8   7
#define jiesuopaodan_control9   8
#define jiesuopaodan_control10   9
#define jiesuopaodan_control11   10
#define jiesuopaodan_control12   11

//残忍退出
#define Form_canrentuichu   18
#define canrentuichu_control1   0
#define canrentuichu_control2   1
#define canrentuichu_control3   2
#define canrentuichu_control4   3

//获得火炮
#define Form_huodehuopao   19
#define huodehuopao_control1   0
#define huodehuopao_control2   1
#define huodehuopao_control3   2
#define huodehuopao_control4   3

//邮箱
#define Form_email   20
#define email_control1   0
#define email_control2   1
#define email_control3   2
#define email_control4   3
#define email_control5   4
#define email_control6   5
#define email_control7   6
#define email_control8   7
#define email_control9   8
#define email_control10   9
#define email_control11   10
#define email_control12   11
#define email_control13   12
#define email_control14   13
#define email_control15   14
#define email_control16   15
#define email_control17   16
#define email_control18   17
#define email_control19   18
#define email_control20   19
#define email_control21   20
#define email_control22   21
#define email_control23   22
#define email_control24   23

//礼品商城
#define Form_lipingshangcheng   21
#define lipingshangcheng_control1   0
#define lipingshangcheng_control2   1
#define lipingshangcheng_control3   2
#define lipingshangcheng_control4   3
#define lipingshangcheng_control5   4
#define lipingshangcheng_control6   5
#define lipingshangcheng_control7   6
#define lipingshangcheng_control8   7
#define lipingshangcheng_control9   8
#define lipingshangcheng_control10   9
#define lipingshangcheng_control11   10
#define lipingshangcheng_control12   11
#define lipingshangcheng_control13   12
#define lipingshangcheng_control14   13
#define lipingshangcheng_control15   14
#define lipingshangcheng_control16   15
#define lipingshangcheng_control17   16
#define lipingshangcheng_control18   17
#define lipingshangcheng_control19   18
#define lipingshangcheng_control20   19
#define lipingshangcheng_control21   20
#define lipingshangcheng_control22   21
#define lipingshangcheng_control23   22
#define lipingshangcheng_control24   23
#define lipingshangcheng_control25   24
#define lipingshangcheng_control26   25
#define lipingshangcheng_control27   26
#define lipingshangcheng_control28   27
#define lipingshangcheng_control29   28

//要2块钱
#define Form_yao2yuan   22
#define yao2yuan_control1   0
#define yao2yuan_control2   1
#define yao2yuan_control3   2
#define yao2yuan_control4   3
#define yao2yuan_control5   4
#define yao2yuan_control6   5

//道具提示框
#define Form_daojutishikuang   23
#define daojutishikuang_control1   0
#define daojutishikuang_control2   1
#define daojutishikuang_control3   2
#define daojutishikuang_control4   3

//通用提示
#define Form_tongyongtishi   24
#define tongyongtishi_control1   0
#define tongyongtishi_control2   1
#define tongyongtishi_control3   2
#define tongyongtishi_control4   3

//解锁炮倍
#define Form_jiesuopaobei   25
#define jiesuopaobei_control1   0
#define jiesuopaobei_control2   1
#define jiesuopaobei_control4   2

#endif
